### ISSUE TITLE
can't build using cocoapods 0.37

### ISSUE THREAD

**Issue by lzyy** [matehat/Objective-LevelDB#24]
```
coding.h:59:7: error: use of undeclared identifier 'port'
```

it seems `GCC_PREPROCESSOR_DEFINITIONS` is not used

**Comment by matehat** [comment]
Trying again and again in different setup from scratch and the project, along with the leveldb-library dependency pod, and everything builds fine. Closing
